#!/bin/bash
# Nek5000 build config file
# (c) 2008,2009,2010 UCHICAGO ARGONNE, LLC

# source path 
#SOURCE_ROOT="$HOME/nek" 

# Fortran compiler
#F77="gfortran -I/opt/openmpi/include -I/opt/openmpi/lib -L/opt/openmpi/lib -lmpi_f90 -lmpi_f77 -lmpi -ldl -lm -Wl,--export-dynamic -lrt -lnsl -lutil  -pg"
CHECKS="-Wall -Wextra -Wno-unused-dummy-argument -pedantic-errors -Wline-truncation -Wunderflow -finit-real=nan -fbacktrace -fcheck=all " #-ffpe-trap=invalid,zero,overflow "
#F77="mpif90  -g -check all -debug all -traceback "
F77="mpif90  "

# C compiler
CC="mpicc "
#CC="gcc -I/opt/openmpi/include -pthread -L/opt/openmpi/lib -lmpi -ldl -lm -Wl,--export-dynamic -lrt -lnsl -lutil -fprofile-arcs -ftest-coverage -pg"

# pre-processor symbol list 
# (set PPLIST=? to get a list of available symbols)
#PPLIST="NO_LAPACK"

# plug-in list
#PLUGIN_LIST=""


# OPTIONAL SETTINGS
# -----------------

# enable MPI (default true)
#IFMPI="false"

# auxilliary files to compile
# NOTE: source files have to located in the same directory as makenek
#       a makefile_usr.inc has to be provided containing the build rules 
#USR=""

# linking flags
#USR_LFLAGS="-lmkl_intel_lp64  -lmkl_sequential -lmkl_core"
USR_LFLAGS="-lblas -llapack -lfftw3"


# generic compiler flags
G=" -ffpe-trap=invalid,zero,overflow -fsignaling-nans -I/usr/include/"

# optimization flags
#OPT_FLAGS_STD=" "
#OPT_FLAGS_MAG=" "

# CVODE path
#CVODE_DIR=$HOME/cvode/lib
 
# MOAB/iMESH path
#MOAB_DIR="$HOME/moab"

# For linking to MOAB, the following might be needed:
# NOTE: compiler specific, use the appropriate one depending on your compiler
# GNU:
# USR_LFLAGS="-lmpi_cxx -lstdc++"
# Intel:
# USR_LFLAGS="-cxxlib"
# PGI:
# USR_LFLAGS="-pgcpplibs"
# USR_LFLAGS=" -lmpi_cxx -lstdc++"

# enable VisIt in situ
#  Note: you can override the lib and include paths. VISIT_LIB and VISIT_INC
#  If VISIT_STOP is set the simulation will stop after first step and wait
#  for VisIt to connect.
#IFVISIT=true
#VISIT_INSTALL="/path/to/visit/current/linux-x86_64/"
#VISIT_STOP=true

###############################################################################
# DONT'T TOUCH WHAT FOLLOWS !!!
###############################################################################
# assign version tag
mver=1
# overwrite source path with optional 2nd argument
if [ -d $2 ] && [ $# -eq 2 ]; then
  SOURCE_ROOT="$2"
  echo "change source code directory to: ", $SOURCE_ROOT
fi
# do some checks and create makefile
source $SOURCE_ROOT/makenek.inc
# compile
make -f makefile 2>&1 | tee compiler.out
if [ -e nek5000 ]; then
  exit 0
else
  exit 1
fi

